---
features:
  - |
    Added configuration parameters ``kolla_enable_tls_internal``,
    ``kolla_internal_fqdn_cert``, and ``kolla_internal_fqdn_cacert`` to
    optionally enable TLS encryption for openstack endpoints on the internal
    network.
