---
- include_tasks: deploy.yml

- name: Check final release (as running on MONs)
  become: true
  shell: docker exec ceph_mon ceph version | cut -d' ' -f5
  changed_when: false
  register: ceph_release_command
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  run_once: true

- name: Finalize the upgrade by disallowing older OSDs
  become: true
  command: docker exec ceph_mon ceph osd require-osd-release {{ ceph_release_command.stdout }}
  changed_when: false
  delegate_to: "{{ groups['ceph-mon'][0] }}"
  run_once: true
