---
- name: Checking gnocchi backend for ceilometer
  fail:
    msg: "gnocchi is required but not enabled"
  run_once: True
  changed_when: false
  when:
    - enable_ceilometer | bool
    - not enable_gnocchi | bool
