---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ monasca_openstack_auth }}"
    service_ks_register_services: "{{ monasca_ks_services }}"
    service_ks_register_users: "{{ monasca_ks_users }}"
  tags: always


- name: Creating monasca roles
  become: true
  kolla_toolbox:
    module_name: os_keystone_role
    module_args:
      name: "{{ item }}"
      region_name: "{{ openstack_region_name }}"
      auth: "{{ monasca_openstack_auth }}"
      endpoint_type: "{{ openstack_interface }}"
      cacert: "{{ openstack_cacert }}"
  run_once: True
  with_items:
    - "{{ monasca_default_authorized_roles }}"
    - "{{ monasca_agent_authorized_roles }}"
    - "{{ monasca_read_only_authorized_roles }}"
    - "{{ monasca_delegate_authorized_roles }}"
