---
- import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_barbican_auth }}"
    service_ks_register_services: "{{ barbican_ks_services }}"
    service_ks_register_users: "{{ barbican_ks_users }}"
  tags: always

- name: Creating default barbican roles
  become: true
  kolla_toolbox:
    module_name: os_keystone_role
    module_args:
      name: "{{ item }}"
      auth: "{{ openstack_barbican_auth }}"
      endpoint_type: "{{ openstack_interface }}"
      cacert: "{{ openstack_cacert }}"
  run_once: True
  with_items:
    - "{{ barbican_keymanager_role }}"
    - "{{ barbican_creator_role }}"
    - "{{ barbican_observer_role }}"
    - "{{ barbican_audit_role }}"
