---
service_ks_register_region_name: "{{ openstack_region_name }}"
service_ks_register_auth: {}
service_ks_cacert: "{{ openstack_cacert }}"
service_ks_register_interface: "{{ openstack_interface }}"
service_ks_register_endpoint_region: "{{ openstack_region_name }}"
service_ks_register_domain: "default"
service_ks_register_delegate_host: "{{ groups['control'][0] }}"
# A list of services to register with Keystone. Each service definition should
# provide a description, service type, and a list of associated endpoints to be
# registered.
service_ks_register_services: []
# A list of users and associated roles for this service to register with Keystone
service_ks_register_users: []
# Number of retries for each task.
service_ks_register_retries: 5
# Delay between task retries.
service_ks_register_delay: 10
