---
- project:
    templates:
      - check-requirements
      - deploy-guide-jobs
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
    check:
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-debian-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-ubuntu-source-multinode-ipv6
        - kolla-ansible-ubuntu-source-ceph
        - kolla-ansible-centos-source-ceph
        - kolla-ansible-ubuntu-source-cinder-lvm
        - kolla-ansible-centos-source-cinder-lvm
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-centos-source-zun
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-centos-source-swift
        - kolla-ansible-ubuntu-source-swift
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-ubuntu-source-masakari
        - kolla-ansible-centos-source-masakari
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-upgrade-ceph
        - kolla-ansible-ubuntu-source-upgrade-ceph
        - kolla-ansible-centos-binary
        - kolla-ansible-ubuntu-binary
        - kolla-ansible-centos-source-cells
        - kolla-ansible-centos-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb
        - kolla-ansible-centos-source-ceph-ansible
        - kolla-ansible-ubuntu-source-ceph-ansible
    check-arm64:
      jobs:
        - kolla-ansible-debian-source-aarch64
    gate:
      queue: kolla
      jobs:
        - kolla-ansible-centos-source
        - kolla-ansible-ubuntu-source
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
    periodic:
      jobs:
        - kolla-ansible-bifrost-centos-source
        - kolla-ansible-centos-source-zun
        - kolla-ansible-ubuntu-source-zun
        - kolla-ansible-ubuntu-source-masakari
        - kolla-ansible-centos-source-masakari
        - kolla-ansible-centos-source-scenario-nfv
        - kolla-ansible-ubuntu-source-cinder-lvm
        - kolla-ansible-centos-source-cinder-lvm
        - kolla-ansible-centos-source-ironic
        - kolla-ansible-centos-binary-ironic
        - kolla-ansible-ubuntu-source-ironic
        - kolla-ansible-centos-source-upgrade
        - kolla-ansible-ubuntu-source-upgrade
        - kolla-ansible-centos-source-upgrade-ceph
        - kolla-ansible-ubuntu-source-upgrade-ceph
        - kolla-ansible-centos-source-mariadb
        - kolla-ansible-ubuntu-source-mariadb
